version: '3.8'

services:
  dokumentum_kereso-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8510:8510"
    volumes:
      - ./data/txt:/app/data/txt:ro
      - ./data/onkorm.db:/app/data/onkorm.db:ro
      - ./data/whoosh_index_dir:/app/data/whoosh_index_dir:ro
    environment:
      - PYTHONUNBUFFERED=1

